### ISSUE TITLE
Run the solution on Simulated IOT Edge 

### ISSUE THREAD

**Issue by ciscosom** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#1]
Greetings , 
Can we deploy this code on a Simulated IOT Edge running on a Windows /Linux docker container (on my laptop) ? If so can you please mention the point at the code/files  that needs to be modified .

**Comment by emmanuel-bv** [comment]
Hello,
I ve just updated this sample to use the latest IoT Edge GA bits and also updated the code+documentation to make it easier to deploy.  It now has instructions on how to deploy on a simulated IoT Edge device.

**Comment by ciscosom** [comment]
Thanks Emmanuel . Let me check and get back to you . Appreciate your help ,
