### ISSUE TITLE
alternative to VS right click instructions

### ISSUE THREAD

**Issue by kbroughton** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#21]
- [x ] documentation issue or request

### Minimal steps to reproduce
> I have installed an azure cli container on my pi following https://github.com/gtrifonov/raspberry-pi-alpine-azure-cli.  This works great.  I'm trying to develop a demo for a class where students will only have a pi - which i can't get VS to run on.  What does VS do when you right click launch it?  If it is an az cli command, I could just run it from the container.

### Any log messages given by the failure
> I tried using the RPI.json template as a deployment but got the following error
     # az iot edge deployment create --content deployment.template.RPI.json --deployment-id texas 
    --login "HostName=myiothub.azure-devices.net;SharedAccessKeyName=iothubowner;DeviceId=mydeviceid;SharedAccessKey=redacted"

but it errors with
> Unauthorized
I was able to get this working but doing an `az login` and using `--hub-name myhubname instead of `--login string`
However, nothing is running on my PI.  Still missing a step.

### Expected/desired behavior
> I would expect there to be an azure cli method for deploying the template in case VS is not available.

### OS and Version?
> Laptop is a Mac.  PI is raspbian 3+ B.

### Versions
> Pulling latest github default branch

**Comment by emmanuel-bv** [comment]
Hi @kbroughton ,
Your RPi does not need to run the az cli commands to connect to a registry. The IoT Edge runtime will take care of connecting to a container registry and downloading the images specified in the deployment.json file.

Will your students have access to a mac or PC (on top of the RPi)? If yes, they will need to install VS Code (which works on mac) with the IoT Edge extension. Deployment to the happen is triggered from VS Code (not from the RPi). See https://github.com/Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#to-deploy-the-solution-on-a-raspberry-pi-3
