### ISSUE TITLE
Does this work with the Pi Camera (not usb)?

### ISSUE THREAD

**Issue by baatch** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#22]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Use Pi camera
### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
Hello, does this work with the pi camera module (not usb)?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by emmanuel-bv** [comment]
The pi camera is not supported for now by the camera-capture module. It only works with USB cameras.
