### ISSUE TITLE
Camera-capture module never runs on Ubuntu

### ISSUE THREAD

**Issue by zambottivinicius** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#24]
- [ x] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
> I'm trying to run this demo on a linux PC and I've created an container registry and uploaded both containers (Image and camera) and also a Linux VM to use as a device. For some reason when I deploy the IoT Edge solution the camera module never starts, even the container does not start or throw any error. And when I start to monitor D2C messages, nothing happens. 

### Any log messages given by the failure
![image](https://user-images.githubusercontent.com/44377574/47310795-8390ef00-d60e-11e8-8bac-2bab4dc12fee.png)

![image](https://user-images.githubusercontent.com/44377574/47310864-a8856200-d60e-11e8-890c-b4b114dcb082.png)

![image](https://user-images.githubusercontent.com/44377574/47311069-31040280-d60f-11e8-9402-dde50c5c425c.png)

### OS and Version?
> Ubuntu 16.04

**Comment by emmanuel-bv** [comment]
@zambottivinicius , Can you try rebooting the device? And could you please provide the logs of the camera-capture module (docker logs camera-capture)? and of post your deployment.json manifest?

It is expected that the camera-capture module exits while the image-classifier is not there yet. It is also expected that messages do not flow to the cloud since the camera-capture module is the one sending them.

**Comment by zambottivinicius** [comment]
I already restarted my device several times using sudo systemctl restart iotedge. Regarding the logs,they're empty.

![image](https://user-images.githubusercontent.com/44377574/47312505-edab9300-d612-11e8-945e-f3963dd38c42.png)

**Comment by zambottivinicius** [comment]
That's my deployment.json 
`{
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "runtime": {
          "type": "docker",
          "settings": {
            "minDockerVersion": "v1.25",
            "loggingOptions": "",
            "registryCredentials": {
              "registryName": {
                "username": "xxxx",
                "password": "xxxx",
                "address": "xxx"
              }
            }
          }
        },
        "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
              "createOptions": ""
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": ""
            }
          }
        },
        "modules": {
          "camera-capture": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "logiotedge.azurecr.io/cameracapture:0.2.7-test-amd64",
              "createOptions": "{\"Env\":[\"VIDEO_PATH=./AppleAndBanana.mp4\",\"IMAGE_PROCESSING_ENDPOINT=http://image-classifier-service:80/image\", \"VERBOSE=TRUE\", \"RESIZE_WIDTH=256\", \"RESIZE_HEIGHT=256\", \"SHOW_VIDEO=TRUE\"], \"HostConfig\":{\"PortBindings\":{\"5012/tcp\":[{\"HostPort\":\"5012\"}]}}}"
            }
          },
          "image-classifier-service": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "logiotedge.azurecr.io/imageclassifierservice:0.2.4-amd64",
              "createOptions": ""
            }
          }
        }
      }
    },
    "$edgeHub": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "routes": {
          "CameraCaptureToIoTHub": "FROM /messages/modules/camera-capture/outputs/output1 INTO $upstream"
        },
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    }
  }
}
`

**Comment by emmanuel-bv** [comment]
It could be because the test-amd64 images does not run the python script but just a open a bash prompt by default. Try:

- using
 the amd64 image directly and add "ADD /test/ ." to the docker file to include your test video file.

OR

- Changing the entry point of the test-amd64.Dockerfile to ENTRYPOINT [ "python", "-u", "./main.py" ] instead of ENTRYPOINT [ "bash" ]

**Comment by zambottivinicius** [comment]
@ebertrams The first solution worked! thank you so much for the help.
