### ISSUE TITLE
Container Status Failed

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#26]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

To deploy the solution on an x64 PC
From your mac or PC:

1. Clone this sample
2. Update the .env file with the values for your container registry and make sure that your docker engine has access to it
3. Rename the deployment.template.json file into deployment.template.RPI.json
4. Rename the deployment.template.test-amd64.json file into deployment.template.json
5. Build the entire solution by right-clicking on the deployment.template.json file and select Build and push IoT Edge Solution (this can take a while...especially to build numpy and pillow...)
6. Deploy the solution to your device by right-clicking on the config/deployment.json file, select Create Deployment for Single device and choose your targeted device

### Any log messages given by the failure

PS C:\WINDOWS\system32> iotedge logs -f camera-capture
Could not convert string to bool.
Could not convert string to bool.
Could not convert string to bool.
Could not convert string to bool.

camera-capture  failed     Failed (1) 16 seconds ago    tuomastest.azurecr.io/cameracapture:0.2.7test-amd64

### Expected/desired behavior
Container Running

### OS and Version?
Windows 10 Enterprise Version 1803

### Versions
Docker version 18.09.0, build 4d60db4
iotedge 1.0.4 (2835ac47fbb944ba628a5cfe812ff394768842e0)
using Docker Linux container 

### Mention any other details that might be useful
I am trying to use my laptop camera to feed the camera-capture module and then send the frames to a Custom Vision API (Object detection so this will not be running on the edge, because it is not available).

Thank you for your help :)
Kind Regards
Haroun

**Comment by emmanuel-bv** [comment]
@ShehataHaroun Sorry a recent bug was introduced when updating the schema of the environment variables of the deployment manifest. This should now be fixed. Please resync your code and give it another shot. Thanks.
