### ISSUE TITLE
Problem with predict.py and labels.txt

### ISSUE THREAD

**Issue by martinabbott** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#29]
When using your own model, the code in predict.py removes the last character of the last label in labels.txt, so any message that is sent through and used directly in the sense-hat display module is missing the last letter of the final classification.

The issue is in the code, line 35 that reads from the labels.txt file and writes to the labels array:

`  l = l[:-1] `

This removes the last character of the last label.

Changing line 35 to the following seems to provide the correct label output
`l = l.strip()`

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

1. Create own model using CustomVision.ai
2. Export DockerFile

3. Copy labels.txt and model.pb to ImageClassifierService module in solution

4. Change version of image-classifier-service in deployment.template.json
5. Build and Push
6. Create deployment for single device

7. Show images as required

8. Output for last label is missing the final letter

### Any log messages given by the failure
>

### Expected/desired behavior
>
Labels should be preserved.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Raspbian Stretch
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by emmanuel-bv** [comment]
https://github.com/Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi/pull/61
