### ISSUE TITLE
Feature Request: Increase FPS for ImageServer 

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#31]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Is it possible to increase the FPS of the ImageServer to 30 so looks like a live stream ?
If this will not be implemented could you give directions on how to change the code in order to achieve this?

Would be a great feature to demonstrate custom vision.

### OS and Version?
Rasbian 9.6

**Comment by emmanuel-bv** [comment]
Performances will depend on your hardware. With this solution, you get about one frame analyzed every 2/3 seconds on a raspberry pi. Going faster woudl require a complete re-architecture of the solution that would be a lot more complex and/or leveraging some hardware accelerators like GPUs.
