### ISSUE TITLE
it will take 6 hours to build CameraCapture.arm32v7 docker file and create module(camera-capture) failed

### ISSUE THREAD

**Issue by czgtest** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#32]
VSCode: 1.31.1
OS: windows10

steps:
### To deploy the solution on a Raspberry Pi 3
From my windows PC:
1. Clone this sample
2. Update the `.env` file with the values for your container registry and make sure that your docker engine has access to it (create azure container registry and docker login in my pc)
3. Build the entire solution by right-clicking on the `deployment.template.json` file and select `Build and push IoT Edge Solution` (this can take a while...especially to build open-cv, numpy and pillow...)

**Issue 1:  It need to run  3 docker file for CameraCapture.arm32v7 & SenseHatDisplay.arm32v7 & ImageClassifierService.arm32v7 image, 
When build CameraCapture.arm32v7 docker file , step5,6,7 will take 6 hours ,  only 70% compiled in 4 and a half hours, it is so slow. Can we improve performance for arm32v7 template?**

4. Deploy the solution to your device by right-clicking on the `config/deployment.json` file, select `Create Deployment for Single device` and choose your targeted device

From my Raspberry pi 3
1.set up edge runtime for pi3
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm
2. setup my edge device connection string
HostName=czghub0214.azure-devices.net;DeviceId=pidevice;SharedAccessKey=orj1Nx1+UuALUIhjWijfm7gpOURAxk4il1Ai42nRR5U=

3. docker login in azure container registry
4. create camera-capture module failed after create deployment for single device on windows pc

**Comment by emmanuel-bv** [comment]
Compiling open-cv is what takes the most build time but it is a one time compilation. If it is still too long for you, your options are to look for pre-compiled open-cv images, there are few available on github but I dont know their quality and maintenance story, that s why this repo compiles open-cv for source.
Note that this repo is made to be used on a linux arm32 device, not on a windows arm32 device.
