### ISSUE TITLE
Camera redirection

### ISSUE THREAD

**Issue by sridhar21111976** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#34]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I am trying to redirect video camera output from windows 10 to the Camera Capture module - is this supported, if yes, whats the procedure

### Any log messages given by the failure
>
cv2.error: OpenCV(4.0.0) /io/opencv/modules/imgproc/src/resize.cpp:3784: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by emmanuel-bv** [comment]
Per my other comment, USB pass-through is on Docker for Windows's backlog but is currently not supported. Alternative is to stream a video feed to your docker VM via a port binding.
