### ISSUE TITLE
moduleContent should be updated to modulesContent in deployment.template.json

### ISSUE THREAD

**Issue by czgtest** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#42]
moduleContent should be updated to modulesContent in deployment.template.json and  deployment.test-amd64.template.json

![image](https://user-images.githubusercontent.com/35018765/54570826-0a5dc280-4a1b-11e9-979f-34bdb4c59180.png)

**Comment by emmanuel-bv** [comment]
Thanks for spotting this. Fixed with Commit 98dd9521f76322fbe2fc63ddb517d7639b0b6937
