### ISSUE TITLE
Build fails for Camera Capture module

### ISSUE THREAD

**Issue by ehjalmar** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#43]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### OS and Version?
> Windows  10.
> Docker 18.09.2
> VS Code 1.32.3
> VS 2017 Enterprise 15.8.1

### Minimal steps to reproduce

I´m gettingan error when trying to build the solution and it seems to be related to CamerCapture module. If i try Docker build one-by-one SenseHatDisplay and ImageClassifier complets without errors.
 
First steps I´ve done to get forward is to replace "resin/raspberrypi3-python:2.7" with "balenalib/raspberrypi3-python:2.7"(resin repository seems to be deprecated?) and changed verison libboost-python to 1.58.0(got a version not found error).

### Any log messages given by the failure
The log output is quite large, but I´ve tried to provied the most important parts here: 

Failed building wheel for numpy
  Running setup.py clean for numpy
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-WbCL8L/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Running from numpy source directory.

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).

Failed cleaning build dir for numpy
Failed to build numpy
Installing collected packages: numpy, certifi, idna, chardet, urllib3, requests, azure-iothub-device-client
  Running setup.py install for numpy: started
    Running setup.py install for numpy: finished with status 'error'
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-WbCL8L/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-QYzXl2/install-record.txt --single-version-externally-managed --compile:
    Running from numpy source directory.

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)
	  
	  
........
	  
	  source = func(extension, build_dir)
      File "numpy/core/setup.py", line 667, in get_mathlib_info
        raise RuntimeError("Broken toolchain: cannot link a simple C program")
    RuntimeError: Broken toolchain: cannot link a simple C program

    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-WbCL8L/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-QYzXl2/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-WbCL8L/numpy/
The command '/bin/sh -c pip install --upgrade pip && pip install --upgrade setuptools && pip install -r arm32v7-requirements.txt' returned a non-zero
code: 1

**Comment by emmanuel-bv** [comment]
Fixed with this PR: https://github.com/Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi/pull/44
