### ISSUE TITLE
build camera-capture module failed on raspberry pi

### ISSUE THREAD

**Issue by czgtest** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#45]
OS: raspberry pi3
steps:

Get started
To deploy the solution on a Raspberry Pi 3
test on raspberry pi3
1.Clone this sample
2.Update the .env file with the values for your container registry and make sure that your docker engine has access to it (create azure container registry and docker login in my pc)
3.build camera-capture module  failed
docker login -u czgacr -p UFQdRXaH4z/qIUVlAIFj191GzGF0GJtj czgacr.azurecr.io
docker build -f Dockerfile.arm32v7 -t czgacr.azurecr.io/cameracapture:0.2.8-arm32v7 .

![image](https://user-images.githubusercontent.com/35018765/57424587-be751000-724a-11e9-8c94-74b950306f8c.png)

**Comment by emmanuel-bv** [comment]
Fixed with https://github.com/Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi/pull/61
