### ISSUE TITLE
[doc]update the document of deploying the solution on Raspberry Pi 3

### ISSUE THREAD

**Issue by czgtest** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#47]
I am confused about the document of deploying the solution on Raspberry Pi 3.
The doc tell user to build and push IoT edge solution on my mac or windows PC.
Why not from my raspberry pi ?  or we need to build modules on my remote raspberry pi.
 
![image](https://user-images.githubusercontent.com/35018765/57438931-86d08d00-7277-11e9-8826-d1d231d8051a.png)

Can you confirm bellow steps are right ?

Test step:
**To deploy the solution on a Raspberry Pi 3**

From your mac or PC:
1.	Clone this sample and open it in VS Code (VS Code should install edge extension)
2.	Open VS Code user setting, enable environment variables for the command executor and Azure IoT Edge terminals by adding the snippet below. In my case, my Pi’s IP is 192.168.86.74, you need change that with your IP or you can also use hostname.
 
![image](https://user-images.githubusercontent.com/35018765/57439071-d1eaa000-7277-11e9-98da-4d3b263b0d3a.png)

3.	Reload VS Code window. Type and run Reload Window in Command Palette.
4.	We will soon use Raspberry Pi to build module images, switch your IoT Edge Default Platform to arm32v7 in the status bar.
 
![image](https://user-images.githubusercontent.com/35018765/57439077-d57e2700-7277-11e9-9caf-3cf14789118c.png)

5.	Update the .env file with the values for your container registry 
6.	Right-clicking on the deployment.template.json file and select Build and push IoT Edge Solution
7.	Deploy the solution to your device by right-clicking on the config/deployment.json file, select Create Deployment for Single device and choose your targeted device
8.	Monitor the messages being sent to the Cloud by right-clicking on your device from the VS Code IoT Edge Extension and select Start Monitoring D2C Message
Note: To stop Device to Cloud (D2C) monitoring, use the Azure IoT Hub: Stop monitoring D2C messages command from the Command Palette (Ctrl+Shift+P).

**Comment by emmanuel-bv** [comment]
The doc is correct. One of the key features of IoT Edge is to push software from the cloud to your devices. So the developer workflow starts with developing code on your dev machine, then you upload that to the cloud (an azure container registry) and then push that to the raspberry pi device thanks to IoT Hub.
