### ISSUE TITLE
Same sample in Windows 10 IoT Core and c#

### ISSUE THREAD

**Issue by JORGEGO** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#49]
Dear our current project it is developed 100% on C#language and Windows 10 IoT Core. 
Any one has migrated current project to C# language.
Any alert about run this way?

Thanks
Kind regards

**Comment by emmanuel-bv** [comment]
Here is an official sample by the windows team that does exactly that: https://github.com/microsoft/Windows-iotcore-samples/blob/1fb6eb4eaf5e488ab4ab544fe7b2abceab7e8afe/Samples/EdgeModules/README.md
