### ISSUE TITLE
How many FPS did you get ?

### ISSUE THREAD

**Issue by abouroubi** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#52]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Just wondering how many FPS did you have on a raspberry pi 3 b + ?

**Comment by emmanuel-bv** [comment]
About 2 seconds / image.
